services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:8080"
    environment:
      - NODE_ENV=production
      - POSTS_DIRECTORY=/app/posts
      - SITE_URL=https://blog.nir.rip
    volumes:
      - ./app/posts:/app/posts:Z
    restart: unless-stopped
